new 'definitions' .md table, typo fixes, .gitignore
hkystar35/MDM pull request #17
Opened 2024-03-28 09:06 UTC by arubdesu

We can certainly refine the wording I put in the definitions table, but I think I captured enough of the intent behind each line item. Open to discuss in MacAdmins slack, I'm [@allister](https://macadmins.slack.com/team/U06AQ7VD5) over there

2024-04-04 10:37 UTC, bochoven approved these changes

2024-04-04 13:31 UTC, hkystar35 commented
I have concerns about the language in this table. I'm currently dealing with a personal matter, though, and won't be able to give it my full attention for a while still.

2024-04-04 14:59 UTC, arubdesu commented
Totally understandable, I used very explicit, opinionated wording so that boundaries were drawn. But we'd want some kind of consensus so that it's fair and consistent enough in tone, I'm fine revising and/or having my choices overridden if I'm off-base or need reeling in. Thanks!

2024-05-02 01:42 UTC, arubdesu commented
Hey, if there's some way I can help make this easier/faster to review please let me know. No pressure, but as an option we can also discuss bringing the whole repo to the MacAdmins Open Source team if you're into the idea of group/community participation in maintenance.

2024-05-21 05:37 UTC, hkystar35 requested changes
Hi again, thanks for your patience, I was out of the country for a while.
I'm happy to make the changes to MDM/README.md, thanks for catching those glaring typos!

I'm still not sure about adding that Definitions table; I see merit in idea, but I'd want to collaborate more closely before adding into the repo.

2024-08-20 04:06 UTC, hkystar35 commented
Here's my counter-proposal:

Keep is all in the same table, but use the `<details>` html tag

```md
| **Feature** | **Category** | **OS** |
|---|---|---|
| <details><summary><b>Local agent/binary</b></summary>A binary agent installed on the local Mac used to augment capabilities beyond just Apple's Device Management framework. Uses the MDM vendor's communication protocol rather that APNs</details> | Agent | macOS |
```

Which gives this look:

| **Feature** | **Category** | **OS** |
|---|---|---|
| <details><summary><b>Local agent/binary</b></summary>A binary agent installed on the local Mac used to augment capabilities beyond just Apple's Device Management framework. Uses the MDM vendor's communication protocol rather that APNs</details> | Agent | macOS |

2024-08-20 04:10 UTC, arubdesu commented
Looks great, will update PR accordingly

2024-10-07 14:11 UTC, arubdesu commented
Whoops, I'm out of date with recent merges but should be able to get synced back up shortly

2024-10-07 14:30 UTC, arubdesu commented
PTAL

2025-03-05 04:14 UTC, hkystar35 approved these changes
Thanks for your patience, finally got around to this. Approved.

2025-03-05 04:14 UTC, merged