Rippling mdm Updates
hkystar35/MDM pull request #27
Opened 2024-12-23 21:16 UTC by kjudie

Adding new MDM Updates for Rippling

2024-12-23 21:32 UTC, kjudie reviewed
Rippling MDM updates

2025-03-05 04:07 UTC, hkystar35 commented
Hi, I know it's been a few months, finally getting some free time to look this over.

I've added a .gitignore to the root of the repo: https://github.com/hkystar35/MDM/blob/main/.gitignore

Please refresh your clone to pull the .gitignore in to your local repo and then re-submit the PR. 

I can't manually ignore the `.DS_Store` files and don't want to add them to the repo.

2025-03-05 04:16 UTC, hkystar35 requested changes
I merged a previous PR from another contributor that reformatted some of the table's content. Sorry, but this will mean a new PR to use the new formatting.

Please also remember to ensure `DS_Store` files are not included in your PR

2025-03-30 14:55 UTC, hkystar35 commented
Closing PR. Please open a new one from a fresh clone

2025-03-30 14:55 UTC, closed without merging